### ISSUE TITLE
Chat Card Optimization: Remove seperate d20 modifier div

### ISSUE THREAD

**Issue by ZeroXNoxus** [tposney/midi-qol#1247]
The additional div only displaying the modifier added to the d20 roll seems unnecessary, especially when compared to the damage roll and the way those modifiers are displayed (merged chat card):
![316335206-ae7d9fb2-09e9-4975-b027-37781d7c163f](https://github.com/tposney/midi-qol/assets/29397572/8d4f3e3f-aa91-4c65-bb3f-0b0c0bc72036)

**Comment by tposney** [comment]
Firstly this is not the active midi-qol repository - you want gitlab.com/tposney/midi-qol. This is just me testing migration from gitlab to git hub.

The extra div is due to how dnd5e renders attack rolls - try rolling with midi disabled and you'll see the same behaviour. Since I rely on dnd5e to render the attack roll tooltip this is probably not going to change.
